// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/reports/my/{userId}": {
            "get": {
                "description": "get MyReports",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "List reports",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Report"
                        }
                    }
                }
            }
        },
        "/reports/upload": {
            "post": {
                "description": "에러 신고에 이미지, 장소, 내용이 담긴다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "에러 신고 업로드",
                "parameters": [
                    {
                        "type": "string",
                        "name": "content",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "ex_location",
                        "name": "location",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Report"
                        }
                    }
                }
            }
        },
        "/reports/{reportId}": {
            "get": {
                "description": "get one of report",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "get report detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "report ID",
                        "name": "reportId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Report"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Report": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image": {
                    "type": "string"
                },
                "location": {
                    "type": "string",
                    "example": "ex_location"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
