definitions:
  model.ReportForm:
    properties:
      content:
        type: string
      latitude:
        example: 37.55327189658719
        type: number
      longtitude:
        example: 126.97232991836047
        type: number
    type: object
info:
  contact: {}
paths:
  /reports:
    get:
      description: get MyReports
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ReportForm'
      summary: List reports
      tags:
      - reports
  /reports/upload:
    post:
      description: 에러 신고에 이미지, 장소, 내용이 담긴다.
      parameters:
      - in: formData
        name: content
        type: string
      - example: 37.55327189658719
        in: formData
        name: latitude
        type: number
      - example: 126.97232991836047
        in: formData
        name: longtitude
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ReportForm'
      summary: 에러 신고 업로드
      tags:
      - reports
swagger: "2.0"
